{% set name = "libcusolver" %}
{% set version = "11.7.5.82" %}
{% set cuda_version = "12.9" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64 and arm_variant_type=="sbsa"]
{% set platform = "linux-aarch64" %}  # [aarch64 and arm_variant_type=="tegra"]
{% set platform = "windows-x86_64" %}  # [win]
{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "ppc64le-linux" %}  # [ppc64le]
{% set target_name = "sbsa-linux" %}  # [aarch64 and arm_variant_type=="sbsa"]
{% set target_name = "aarch64-linux" %}  # [aarch64 and arm_variant_type=="tegra"]
{% set target_name = "x64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/{{ name }}/{{ platform }}/{{ name }}-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: 3d3b96f3087dbc43893a28691b172f31725b316d524f5a3c1e6837257c898d06  # [linux64]
  sha256: db463593ffcbc78f542a7f1ef808da43bf742acae654d970d99a47289c2a83e5  # [aarch64 and arm_variant_type=="sbsa"]
  sha256: 45e2fefeee5797c0492d8a9ee26c3dbb7af0cdcefe6f1cd25bd586daa633d9a0  # [aarch64 and arm_variant_type=="tegra"]
  sha256: e991d64a0bbe3e0bb69ce2adce000244288002b0341894729666d66adb9b4f25  # [win]

build:
  number: 2
  skip: true  # [osx or ppc64le]
  script_env:
    - component_name={{ name }}

requirements:
  build:
    - arm-variant * {{ arm_variant_type }}  # [aarch64]
    - {{ stdlib("c") }}
    - patchelf <0.18.0                      # [linux]
    - cf-nvidia-tools 1.*                   # [linux]

outputs:
  - name: libcusolver
    build:
      binary_relocation: false
    files:
      - lib/libcusolver*.so.*                            # [linux]
      - targets/{{ target_name }}/lib/libcusolver*.so.*  # [linux]
      - Library\bin\cusolver*.dll                        # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - {{ stdlib("c") }}
        - patchelf <0.18.0                      # [linux]
      host:
        - cuda-version {{ cuda_version }}
        - libcublas
        - libcusparse
        - libnvjitlink =={{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - {{ pin_compatible("libcublas", max_pin="x.x") }}
        - {{ pin_compatible("libcusparse", max_pin="x.x") }}
        - {{ pin_compatible("libnvjitlink", max_pin="x") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      requires:
        - patchelf  # [linux]
      files:
        - test-rpath.sh
      commands:
        - test -L $PREFIX/lib/libcusolver.so.{{ version.split(".")[0] }}    # [linux]
        - test -L $PREFIX/lib/libcusolver.so.{{ version }}                  # [linux]
        - test -L $PREFIX/targets/{{ target_name }}/lib/libcusolver.so.{{ version.split(".")[0] }}    # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/lib/libcusolver.so.{{ version }}                  # [linux]
        - test -L $PREFIX/lib/libcusolverMg.so.{{ version.split(".")[0] }}  # [linux]
        - test -L $PREFIX/lib/libcusolverMg.so.{{ version }}                # [linux]
        - test -L $PREFIX/targets/{{ target_name }}/lib/libcusolverMg.so.{{ version.split(".")[0] }}  # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/lib/libcusolverMg.so.{{ version }}                # [linux]
        - bash test-rpath.sh                                                                          # [linux]
        - if not exist %LIBRARY_BIN%\cusolver*.dll exit 1                  # [win]
        - if not exist %LIBRARY_BIN%\cusolverMg*.dll exit 1                # [win]
    about:
      home: https://developer.nvidia.com/cusolver
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: CUDA Linear Solver Library
      description: |
        cuSOLVER - Direct Linear Solvers on NVIDIA GPUs
      doc_url: https://docs.nvidia.com/cuda/cusolver/

  - name: libcusolver-dev
    build:
      binary_relocation: false
      run_exports:
        - {{ pin_subpackage("libcusolver", max_pin="x") }}
    files:
      - lib/libcusolver*.so               # [linux]
      - lib/pkgconfig                     # [linux]
      - targets/{{ target_name }}/include              # [linux]
      - targets/{{ target_name }}/lib/libcusolver*.so  # [linux]
      - targets/{{ target_name }}/lib/stubs            # [linux]
      # Not shipping Fortran bindings (in src) on Windows for now
      - targets/{{ target_name }}/libcusolver/src      # [linux]
      - Library\include                                # [win]
      - Library\lib                                    # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - {{ pin_subpackage("libcusolver", exact=True) }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
      run_constrained:
        - libcusolver-static >={{ version }}      # [linux]
    test:
      commands:
        - test -L $PREFIX/lib/libcusolver.so                                # [linux]
        - test -L $PREFIX/lib/libcusolverMg.so                              # [linux]
        - test -f $PREFIX/lib/pkgconfig/cusolver*.pc                        # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/include/cusolverDn.h                   # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/include/cusolverMg.h                   # [aarch64 and arm_variant_type!="tegra"]
        - test -f $PREFIX/targets/{{ target_name }}/include/cusolverRf.h                   # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/include/cusolverSp.h                   # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/include/cusolverSp_LOWLEVEL_PREVIEW.h  # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/include/cusolver_common.h              # [linux]
        - test -L $PREFIX/targets/{{ target_name }}/lib/libcusolver.so                     # [linux]
        - test -L $PREFIX/targets/{{ target_name }}/lib/libcusolverMg.so                   # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/lib/stubs/libcusolver.so               # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/lib/stubs/libcusolverMg.so             # [linux]
        - if not exist %LIBRARY_INC%\cusolverDn.h exit 1                   # [win]
        - if not exist %LIBRARY_INC%\cusolverMg.h exit 1                   # [win]
        - if not exist %LIBRARY_INC%\cusolverRf.h exit 1                   # [win]
        - if not exist %LIBRARY_INC%\cusolverSp.h exit 1                   # [win]
        - if not exist %LIBRARY_INC%\cusolverSp_LOWLEVEL_PREVIEW.h exit 1  # [win]
        - if not exist %LIBRARY_INC%\cusolver_common.h exit 1              # [win]
        - if not exist %LIBRARY_LIB%\cusolver*.lib exit 1                  # [win]
        - if not exist %LIBRARY_LIB%\cusolverMg*.lib exit 1                # [win]
    about:
      home: https://developer.nvidia.com/cusolver
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: CUDA Linear Solver Library
      description: |
        cuSOLVER - Direct Linear Solvers on NVIDIA GPUs
      doc_url: https://docs.nvidia.com/cuda/cusolver/index.html

  - name: libcusolver-static
    build:
      skip: true  # [win]
      binary_relocation: false
    files:
      - targets/{{ target_name }}/lib/libcusolver*_static.a
      - targets/{{ target_name }}/lib/libmetis_static.a
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_version }}
        - libcublas-static
        - libcusparse-static
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - {{ pin_compatible("libcublas-static", max_pin="x.x") }}
        - {{ pin_compatible("libcusparse-static", max_pin="x.x") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      commands:
        - test -f $PREFIX/targets/{{ target_name }}/lib/libcusolver_static.a
        - test -f $PREFIX/targets/{{ target_name }}/lib/libcusolver_lapack_static.a
        - test -f $PREFIX/targets/{{ target_name }}/lib/libcusolver_metis_static.a
        - test -f $PREFIX/targets/{{ target_name }}/lib/libmetis_static.a
    about:
      home: https://developer.nvidia.com/cusolver
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: CUDA Linear Solver Library
      description: |
        cuSOLVER - Direct Linear Solvers on NVIDIA GPUs
      doc_url: https://docs.nvidia.com/cuda/cusolver/index.html

about:
  home: https://developer.nvidia.com/cusolver
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: CUDA Linear Solver Library
  description: |
    cuSOLVER - Direct Linear Solvers on NVIDIA GPUs
  doc_url: https://docs.nvidia.com/cuda/cusolver/index.html

extra:
  feedstock-name: {{ name }}
  recipe-maintainers:
    - conda-forge/cuda
